package com.example.timetonictest.remote.model.book

data class LastMsg(
    val b_c: String,
    val b_o: String,
    val created: Int,
    val del: Boolean,
    val docs: List<Doc>,
    val lastCommentId: Int,
    val lastModified: Int,
    val linkMessage: String,
    val linkedFieldId: String,
    val linkedRowId: String,
    val linkedTabId: String,
    val medias: List<Media>,
    val msg: String,
    val msgBody: String,
    val msgColor: String,
    val msgMethod: String,
    val msgType: String,
    val nbComments: Int,
    val nbDocs: Int,
    val nbEmailCids: Int,
    val nbMedias: Int,
    val pid: Int,
    val smid: Int,
    val sstamp: Long,
    val u_c: String,
    val uuid: String
)